default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    args: [
      --ignore-words=.codespellignore
    ]
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: fmt
    args: [
      --all,
      --,
    ]
  - id: cargo-check
    args: [
      --locked,
      --workspace,
      --all-features,
      --all-targets,
    ]
  - id: clippy
    args: [
      --locked,
      --workspace,
      --all-features,
      --all-targets,
      --,
      -D,
      warnings,
    ]
- repo: https://github.com/Holzhaus/sourceheaders
  rev: v0.0.4
  hooks:
  - id: sourceheaders
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
