[package]
name = "rekordcrate"
version = "0.3.0"
authors = ["Jan Holthuis <jan.holthuis@ruhr-uni-bochum.de>"]
description = "Library for parsing Pioneer Rekordbox device exports"
readme = "README.md"
repository = "https://github.com/Holzhaus/rekordcrate"
license = "MPL-2.0"
keywords = ["rekordbox", "dj", "export", "database", "parser"]
categories = ["parser-implementations"]
edition = "2021"
exclude = [".*"]

[dependencies]
binrw = "0.15"
modular-bitfield = "0.13"
crc16 = "0.4"
clap = { version = "4.6", features = ["derive"], optional = true }
parse-display = "0.11"
thiserror = "2.0"
quick-xml = { version = "0.40.1", features = ["serialize", "serde-types"], optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
serde_repr = { version = "0.1.19", optional = true }
faster-hex = { version = "0.9", optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
rgb = { version = "0.8", optional = true }
fallible-iterator = "0.3.0"
diesel = { version = "2.3.7", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "64-column-tables"], optional = true }
diesel-derive-newtype = { version = "2.1.2", optional = true }
libsqlite3-sys = { version = "0.36.0", features = ["bundled-sqlcipher"], optional = true }

[build-dependencies]
glob = "0.3"

[dev-dependencies]
pretty-hex = "0.4"
pretty_assertions = "1"
tempfile = "3"

[features]
default = ["cli", "xml", "json"]
cli = ["dep:clap"]
xml = ["dep:serde", "dep:serde_repr", "dep:quick-xml", "dep:chrono", "dep:rgb"]
json = ["dep:serde", "dep:serde_json", "dep:faster-hex"]
device_library_plus = ["dep:diesel", "dep:diesel-derive-newtype", "dep:libsqlite3-sys"]

[[bin]]
name = "rekordcrate"
required-features = ["cli"]
